#!/bin/sh
# Add here your email address
#NOTIFY_ADDRESS=

if [ $# -eq 0 ]; then
    echo "Usage: $0 <command-with-arguments>"
    echo "\tAnd don't forget to set NOTIFY_ADDRESS somewhere"
    exit 1
fi

eval $@
exit_status=$?

# Check if the command was successful
if [ $exit_status -eq 0 ]; then
    subject="finished successfully"
    body="The command \"$@\" completed successfully"
else
    subject="failed"
    body="The command \"$@\" failed with exit code $exit_status"
fi

printf "Subject: Command $1 on $(hostname) $subject\r\n$body at $(date)." | msmtp -a notify $NOTIFY_ADDRESS

# Exit with the same status as the executed command
exit $exit_status
